export const ON_FORM_SUBMIT = 'ON_FORM_SUBMIT'
export const REQUEST_PEOPLE_DATA_PENDING = 'REQUEST_PEOPLE_DATA_PENDING';
export const REQUEST_PEOPLE_DATA_SUCCESS = 'REQUEST_PEOPLE_DATA_SUCCESS';
export const REQUEST_PEOPLE_DATA_FAILED = 'REQUEST_PEOPLE_DATA_FAILED';
export const ON_REMOVE_PERSON = 'ON_REMOVE_PERSON'; 
