export const CHANGE_ADD_FIELD = 'CHANGE_ADD_FIELD'
export const ON_FORM_SUBMIT = 'ON_FORM_SUBMIT'
export const REQUEST_DUMMY_DATA_PENDING = 'REQUEST_DUMMY_DATA_PENDING';
export const REQUEST_DUMMY_DATA_SUCCESS = 'REQUEST_DUMMY_DATA_SUCCESS';
export const REQUEST_DUMMY_DATA_FAILED = 'REQUEST_DUMMY_DATA_FAILED';
export const ON_REMOVE_PERSON = 'ON_REMOVE_PERSON'; UPDATE_PEOPLE_STORAGE
export const UPDATE_PEOPLE_STORAGE = 'UPDATE_PEOPLE_STORAGE'; 