export const CHANGE_ADD_FIELD = 'CHANGE_ADD_FIELD'
export const ON_FORM_SUBMIT = 'ON_FORM_SUBMIT'
export const REQUEST_PEOPLE_DATA_PENDING = 'REQUEST_PEOPLE_DATA_PENDING';
export const REQUEST_PEOPLE_DATA_SUCCESS = 'REQUEST_PEOPLE_DATA_SUCCESS';
export const REQUEST_PEOPLE_DATA_FAILED = 'REQUEST_PEOPLE_DATA_FAILED';
export const ON_REMOVE_PERSON = 'ON_REMOVE_PERSON'; 
export const PEOPLE_USER_INTERFACE_UPDATE = 'PEOPLE_USER_INTERFACE_UPDATE'; 
